services:
  - type: web
    name: braintree-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn braintreeapi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
